server:
  port: 1101
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: web-serverp
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:1000/