spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gongzhifei/config-center.git
          search-paths: config-repository/
          username: gongzhifei
          password: ''
server:
  port: 1000
